name: ChunLokMah
favicon: null
layout_spectrum: 0.6900941494386643
typography_spectrum: 0.57391
title: 'ChunLok Mah Art & Design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#76757a'
    - '#444348'
    - '#18211e'
    - '#070204'
    - '#97a99d'
  brandStrength: 0.5
  lightness: 0.7861520971637219
  saturation: 0.5
  rhythmicContrast: 0.18356536235660315
purpose: []
